export const OTP_CONSTANTS = {
  MIN_MAX_TRIES: 1,
  MAX_MAX_TRIES: 10,
  DEFAULT_MAX_TRIES: 3,
  MIN_VALID_TIME_MINUTES: 1,
  MAX_VALID_TIME_MINUTES: 60,
  DEFAULT_VALID_TIME_MINUTES: 5,
} as const;
