export const SMS_CONSTANTS = {
  MAX_MESSAGE_LENGTH: 1005,
  MAX_CAMPAIGN_NAME_LENGTH: 50,
  MAX_SOURCE_LENGTH: 11,
  MAX_BULK_MESSAGES: 2500,
  UNSUBSCRIBE_OPTIONS: {
    REPLY: '2',
    LINK: '3',
  },
  TEMP_BL_MIN_DAYS: 1,
  TEMP_BL_MAX_DAYS: 14,
  BOOLEAN_FLAGS: {
    ENABLED: '1',
    DISABLED: '0',
  },
} as const;
