export const CONFIG_KEYS = {
  PORT: 'PORT',
  NODE_ENV: 'NODE_ENV',
  TEXTME_BASE_URL: 'TEXTME_BASE_URL',
  TEXTME_TEST_URL: 'TEXTME_TEST_URL',
  TEXTME_API_TOKEN: 'TEXTME_API_TOKEN',
  TEXTME_USERNAME: 'TEXTME_USERNAME',
  TEXTME_SOURCE: 'TEXTME_SOURCE',
  TEXTME_IS_TEST_MODE: 'TEXTME_IS_TEST_MODE',
  TEXTME_TIMEOUT_MS: 'TEXTME_TIMEOUT_MS',
  CORS_ORIGIN: 'CORS_ORIGIN',
} as const;

export const CONFIG_DEFAULTS = {
  PORT: 3001,
  NODE_ENV: 'development',
  TEXTME_BASE_URL: 'https://my.textme.co.il',
  TEXTME_TEST_URL: 'https://my.textme.co.il/api/test',
  TEXTME_IS_TEST_MODE: false,
  TEXTME_TIMEOUT_MS: 30000,
  CORS_ORIGIN: '*',
} as const;
