export const API_CONSTANTS = {
  DEFAULT_PORT: 3001,
  GLOBAL_PREFIX: 'api',
  PROD_BASE_URL: 'https://my.textme.co.il',
  LIVE_ENDPOINT_PATH: '/api',
  TEST_ENDPOINT_PATH: '/api/test',
  AUTH_HEADER_PREFIX: 'Bearer ',
  HEADER_CONTENT_TYPE: 'Content-Type',
  HEADER_AUTHORIZATION: 'Authorization',
  CONTENT_TYPE_JSON: 'application/json',
  CONTENT_TYPE_FORM: 'application/x-www-form-urlencoded',
  DEFAULT_TIMEOUT_MS: 30000,
  DEFAULT_MAX_RETRIES: 2,
  RETRY_INITIAL_DELAY_MS: 500,
} as const;

export const TEXTME_OPERATIONS = {
  GET_API_TOKEN: 'getApiToken',
  SEND_SMS: 'sms',
  SEND_BULK: 'bulk',
  SEND_OTP: 'send_otp',
  VALIDATE_OTP: 'validate_otp',
  BALANCE: 'balance',
  DLR: 'dlr',
  DLR_BY_DATE: 'dlrByDate',
  INCOMING: 'incoming',
  BLACKLIST_GET: 'blacklist',
  BLACKLIST_ADD: 'addNumBL',
  BLACKLIST_REMOVE: 'rmNumBL',
  CL_CREATE: 'newCL',
  CL_REMOVE: 'removeCL',
  CL_ADD_NUMBERS: 'addNumCL',
  CL_REMOVE_NUMBERS: 'rmNumCL',
  CL_GET_ALL: 'getCL',
  CL_GET_BY_ID: 'getCLbyID',
  CAMPAIGN_CANCEL: 'cancel',
  CAMPAIGN_BIRTHDAY_LIST: 'get_birthday_campaigns',
  CAMPAIGN_BIRTHDAY_EDIT: 'edit_birthday_campaign',
  VERIFY_PHONE: 'verify_phone',
  GET_VERIFIED_PHONES: 'getVerifiedPhones',
  PUSH_URL: 'push_url',
  SUBSCRIBER_ADD: 'addSub',
  SUBSCRIBER_UPDATE_WALLET: 'updateAmountSub',
  SUBSCRIBER_BALANCES: 'getBlanceSubs',
} as const;

export type TextMeOperationKey = typeof TEXTME_OPERATIONS[keyof typeof TEXTME_OPERATIONS];
