export const TEXTME_STATUS = {
  SUCCESS: 0,
  XML_PARSE_ERROR: 1,
  MISSING_REQUIRED_FIELD: 2,
  INVALID_CREDENTIALS: 3,
  NOT_ENOUGH_CREDIT: 4,
  NO_PERMISSION_SEND_HOURS: 5,
  PROCESS_FAILURE: 6,
  INVALID_BULK_FORMAT: 7,
  ALL_NUMBERS_BLOCKED: 8,
  PHONE_LENGTH_INVALID: 9,
  EXPIRED_TOKEN: 10,
  TOKEN_MISMATCH: 11,
  NOT_ENOUGH_MONEY_OR_UNVERIFIED_OTP: 12,
  INVALID_ACTION_TYPE: 502,
  USERNAME_NOT_IN_ACCOUNT: 503,
  CURRENT_TOKEN_NOT_FOUND: 504,
  VERIFY_PHONE_NO_PHONES: 510,
  NO_PERMISSION_FOR_FUNCTION: 511,
  UNVERIFIED_SOURCE: 515,
  PUSH_URL_ALREADY_EXISTS: 517,
  TEMP_BL_INVALID: 714,
  ALL_NUMBERS_TEMP_BLOCKED: 715,
  PHONE_OR_REASON_NOT_VALID: 933,
  BLOCKLIST_PARTIAL_REMOVAL: 944,
  BLOCKLIST_ADDED: 946,
  CAMPAIGN_ALREADY_CANCELLED: 955,
  CAMPAIGN_ALREADY_SENT: 966,
  CAMPAIGN_NOT_CANCELLED: 970,
  CAMPAIGN_NOT_EXIST_OR_NOT_OWNED: 977,
  INVALID_LINK: 980,
  ERROR_CREATE_HASH: 981,
  ADD_UNSUBSCRIBE_INVALID: 986,
  CONTACT_LIST_NOT_FOUND: 988,
  MESSAGE_TOO_LONG_OR_SHORT: 989,
  SUBSCRIBER_AMOUNT_EXCEEDS_CREDIT: 990,
  SUBSCRIBER_AMOUNT_NOT_NUMERIC: 991,
  SUBSCRIBER_SOURCE_LENGTH_INVALID: 992,
  SUBSCRIBER_PASSWORD_LENGTH_INVALID: 993,
  SUBSCRIBER_USERNAME_EXISTS: 994,
  SUBSCRIBER_USERNAME_LENGTH_INVALID: 995,
  SUBSCRIBER_NAME_LENGTH_INVALID: 996,
  INVALID_COMMAND: 997,
  UNKNOWN_ERROR: 998,
  CONTACT_SUPPORT: 999,
} as const;

export type TextMeStatusCode = typeof TEXTME_STATUS[keyof typeof TEXTME_STATUS];

export function isTextMeSuccess(statusCode: number, operation?: string): boolean {
  if (statusCode === TEXTME_STATUS.SUCCESS) {
    return true;
  }
  // addNumBL returns 946 on success
  if (operation === 'addNumBL' && statusCode === TEXTME_STATUS.BLOCKLIST_ADDED) {
    return true;
  }
  // rmNumBL returns 944 on partial success
  if (operation === 'rmNumBL' && statusCode === TEXTME_STATUS.BLOCKLIST_PARTIAL_REMOVAL) {
    return true;
  }
  return false;
}
